### ISSUE TITLE
error processing incoming message: vclock encoding

### ISSUE THREAD

**Issue by pgte** [nlf/riakpbc#5] opened 2013-04-09 16:07 UTC
I have this riak error at the protobuf level:

```
err Error processing incoming message: throw:{error,"Error decodeing type"}:[{protobuffs,
                                                                          read_field_num_and_wire_type,
                                                                          1,
                                                                          [{file,
                                                                            "src/protobuffs.erl"},
                                                                           {line,
                                                                            203}]},
```

I've nailed it down to the `vclock` value when updating a record.

As the vclock comes back as a buffer, I encode it as a base64 string for replying to clients.
When updating a record, I encode it back as a buffer, resulting in the same exact bytes as the original reply:

```
reply.vlock: <Buffer 6b ce 61 60 60 60 cc 60 ca 05 52 1c ca 9c ff 7e 06 26 dd 38 9b c1 94 c8 98 c7 ca 30 77 fb 8d 53 7c 59 00>
(...)
options.vclock <Buffer 6b ce 61 60 60 60 cc 60 ca 05 52 1c ca 9c ff 7e 06 26 dd 38 9b c1 94 c8 98 c7 ca 30 77 fb 8d 53 7c 59 00>
```

I've tried it as an utf-8 encoded string, but this time getting an error on the zlib level:

``````
options.vclock k�a```�`�Rʜ�~&�8���Ș������)�,

rr Error processing incoming message: error:data_error:[{zlib,call,3,[]},
                                                     {zlib,inflate,2,[]},
                                                     {zlib,unzip,1,[]},
                                                     {riak_kv_pb_object,
                                                      erlify_rpbvc,1,
``````

Any clue or hint?

TIA!

**Comment by nlf** [comment] 2013-04-09 16:14
This sounds like the value isn't being encoded into the protobuf message being sent to riak properly, how were you able to determine that it was the vclock? How are you doing the conversion to base64 and back?

**Comment by pgte** [comment] 2013-04-09 16:24
I determined that it was the vclock because the call works without the vclock attribute, (but creates a sibling, as expected).

I convert to base64 using `reply.vclock.toString('base64')` and I convert back to buffer by using `new Buffer(clock, 'base64')`.

I don't think that the conversion is the problem since, as you can see, the buffer bytes are exactly the same what I get from the `.get()` call.

I'd be happy to do a PR with a failing test case if you need, but I would like to know if I'm making something blatantly wrong first ;)

**Comment by nlf** [comment] 2013-04-09 16:26
Nope, this definitely sounds like a bug. A PR with a failing test would be great, then I'll see if I can find the root cause and get it fixed. Thanks for reporting it.

**Comment by nlf** [comment] 2013-04-09 17:08
fixed by nlf/protobuf.js@66cb36eed97dad584de17409c144251da66094d2

update to riakpbc 0.0.9 and confirm, but your failing test now passes.

**Closed as completed by nlf** 2013-04-09 17:08 UTC
