### ISSUE TITLE
Sending empty or non-string value.

### ISSUE THREAD

**Issue by calebcase** [nlf/riakpbc#32] opened 2013-12-10 18:58 UTC
Starting from a fresh install of Riak 1.4.2-1 (ubuntu/basho packages).

```
$ curl -is 'http://127.0.0.1:8098/buckets/people/keys/empty'
HTTP/1.1 404 Object Not Found
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Tue, 10 Dec 2013 18:32:28 GMT
Content-Type: text/plain
Content-Length: 10

not found
```

Put empty data in:

```
$ curl -i -H 'Content-Type: application/json' -X PUT 'http://127.0.0.1:8098/buckets/people/keys/empty' -d ''
HTTP/1.1 204 No Content
Vary: Accept-Encoding
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Tue, 10 Dec 2013 18:35:03 GMT
Content-Type: application/json
Content-Length: 0

```

Everything appears well:

```
$ curl -is 'http://127.0.0.1:8098/buckets/people/keys/empty'
HTTP/1.1 200 OK
X-Riak-Vclock: a85hYGBgzGDKBVIcypz/fgYtj7PIYEpkzGNluH5L+gxfFgA=
Vary: Accept-Encoding
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Link: </buckets/people>; rel="up"
Last-Modified: Tue, 10 Dec 2013 18:35:03 GMT
ETag: "1MvrYundbdRZA34IOByQVF"
Date: Tue, 10 Dec 2013 18:35:28 GMT
Content-Type: application/json
Content-Length: 0

```

Now restesting with riakpbc:

```
$ cat test-empty-put.coffee
riakpbc = require 'riakpbc'
client = riakpbc.createClient()

options =
  bucket: 'person'
  key: 'empty'
  content:
    content_type: 'application/json'
    value: ''
client.put options, (error, reply) ->
  console.log error, reply
  client.disconnect()
$ coffee test-empty-put.coffee
undefined {}
$ cat test-emtpy-get.coffee
riakpbc = require 'riakpbc'
client = riakpbc.createClient()

options =
  bucket: 'person'
  key: 'empty'
  notfound_ok: true
client.get options, (error, reply) ->
  console.log error, reply
  client.disconnect()
$ coffee test-empty-get.coffee

undefined:0

^
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at parseContent (/home/ccase/link-walking/node_modules/riakpbc/lib/parse-content.js:16:27)
  at Array.forEach (native)
  at processSingleResBuffer (/home/ccase/link-walking/node_modules/riakpbc/index.js:140:30)
  at Array.forEach (native)
  at RiakPBC.processAllResBuffers (/home/ccase/link-walking/node_modules/riakpbc/index.js:116:16)
  at RiakPBC._processPacket (/home/ccase/link-walking/node_modules/riakpbc/index.js:108:26)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

HTTP interface still thinks everything is ok:

```
$ curl -is 'http://127.0.0.1:8098/buckets/people/keys/empty'
HTTP/1.1 200 OK
X-Riak-Vclock: a85hYGBgzGDKBVIcypz/fgYtj7PIYEpkzGNluH5L+gxfFgA=
Vary: Accept-Encoding
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Link: </buckets/people>; rel="up"
Last-Modified: Tue, 10 Dec 2013 18:35:03 GMT
ETag: "1MvrYundbdRZA34IOByQVF"
Date: Tue, 10 Dec 2013 18:38:55 GMT
Content-Type: application/json
Content-Length: 0

```

But now the protobuf interface is in a bad state.

Removing the document doesn't fix it:

```
$ curl -is -X DELETE 'http://127.0.0.1:8098/buckets/people/keys/empty'
HTTP/1.1 204 No Content
Vary: Accept-Encoding
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Tue, 10 Dec 2013 18:41:19 GMT
Content-Type: application/json
Content-Length: 0

$ coffee test-empty-get.coffee

undefined:0

^
SyntaxError: Unexpected end of input
  at Object.parse (native)
  at parseContent (/home/ccase/link-walking/node_modules/riakpbc/lib/parse-content.js:16:27)
  at Array.forEach (native)
  at processSingleResBuffer (/home/ccase/link-walking/node_modules/riakpbc/index.js:140:30)
  at Array.forEach (native)
  at RiakPBC.processAllResBuffers (/home/ccase/link-walking/node_modules/riakpbc/index.js:116:16)
  at RiakPBC._processPacket (/home/ccase/link-walking/node_modules/riakpbc/index.js:108:26)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

Ditto if I now put a new empty document in via HTTP. In fact, even putting in a new non-empty document with actual data doesn't fix it (with the same 'empty' key). Restarting the riak service doesn't fix it either (same behavior, all good via HTTP, but the protobuf is broken).

On the other hand, it is specific to this key 'empty'. Putting in more documents works (as long as you don't make the same mistake).

So far the only way I've been able to come back from this is to manually delete the bucket's files from var.

I innocently stumbled up this by accidentally not converting the value to a JSON string:

```
$ cat test-invalid-put.coffee
riakpbc = require 'riakpbc'
client = riakpbc.createClient()

options =
  bucket: 'person'
  key: 'empty'
  content:
    content_type: 'application/json'
    value:
      oops: "Should have stringified..."
client.put options, (error, reply) ->
  console.log error, reply
  client.disconnect()
```

Which has the surprising behaviors of not automatically converting value to a string and sending an empty string to riak.

**Comment by nlf** [comment] 2013-12-10 19:04
Confirmed.

This occurs because of the content-type being set to application/json, but the value being an empty string. Currently, riakpbc interprets the value as a buffer with no contents, which JSON.parse is unable to parse causing the crash. I'll have a fix for this pushed momentarily.

**Closed as completed** 2013-12-10 19:06 UTC

**Comment by nlf** [comment] 2013-12-10 19:07
Just published version 1.0.5 which should resolve this issue.

I'll have to do some thinking about whether or not to automatically stringify json if an object is passed instead of a string for the value field.

**Comment by calebcase** [comment] 2013-12-10 19:10
Awesome! Thanks for the fast response and quick fix!

**Comment by nisaacson** [comment] 2013-12-10 19:43
@nlf nice work!
