### ISSUE TITLE
getKeys() error 'Trying to access beyond buffer length'

### ISSUE THREAD

**Issue by kylegetson** [nlf/riakpbc#81] opened 2014-10-09 16:52 UTC
When I have a large number of maps in a bucket, and call getKeys, I get the error 'Trying to access beyond buffer length'. I have the problem intermittently when I have around 35,000 maps in the bucket, which seems very odd but another bucket has hundreds of thousands of maps in it, and it gives me this error every time. From what I can tell from Riak's documentation, this should still work regardless of the number of keys.

```
buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
    ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readInt32BE (buffer.js:750:5)
```

**Comment by nlf** [comment] 2014-10-09 17:01
Is this on the newest release of riakpbc? Version 2.0.3?

**Comment by kylegetson** [comment] 2014-10-09 17:17
yes

**Comment by nlf** [comment] 2014-10-09 17:20
And you're only able to reproduce this reliably in the case of having hundreds of thousands of keys in a bucket?

**Comment by kylegetson** [comment] 2014-10-09 17:32
Yes, although I'm not sure at what point it started happening, I just was curious how big a bucket was, and ran into that issue.

**Comment by nlf** [comment] 2014-10-09 17:32
I'll see what I can come up with to test this.

**Comment by kylegetson** [comment] 2014-10-10 04:36
I wrote a quick script to test this in varying increments. It seems to be very environment dependent. On my macbook pro (8G memory), I could get up to 600,000 keys before I get this error, but once I start getting it, it happens most of the time (but not every time). On an ec2 instance (4G memory amazon AMI) I can only get to 38,000 before it starts happening, but it happens very rarely, when I got to about 45,000 the errors were much more common.  I'll need to look through the configuration differences between the two installs.

```
var RiakPBC = require('riakpbc');
var client = RiakPBC.createClient({
  host: "...",
  port: "8087"
});
// need to do somethign better with this
var BUCKET_TYPE = 'mycustombucket';
var uuid = require('node-uuid');

function getCount(cb) {
  var allKeys = [];
  console.log('getting count...');
  client.getKeys({
    bucket: 'limit-test',
    type: BUCKET_TYPE
  }).on('data', function (reply) {
    reply.keys.forEach(function (k) {
      allKeys.push(k);
    });
  }).on('end', function (data) {
    console.log('there are ' + allKeys.length + ' keys');
  });
}


function put(num, done) {
  if (num <= 0) {
    console.log('done');
    done();
    return;
  }
  //console.log('putting ' + num);
  var key = uuid.v4();
  client.putCrdt({
    bucket: 'limit-test',
    key: key,
    type: BUCKET_TYPE,
    op: {
      map_op: {
        updates: [{
          field: {
            name: 'whatever',
            type: RiakPBC.FieldType.Register
          },
          register_op: '...'
        }]
      }
    },
    return_body: true
  }, function (err, reply) {
    if (err) return callback(err);
    return put(--num, done);
  });
}

// start by getting a count
getCount();

// run it through a bunch of times, when done it will get a count
put(1000, function () {
  getCount();
});
```

**Comment by nlf** [comment] 2014-10-22 17:01
So I was able to reproduce this somewhat sporadically, with occasionally the script just stopping with no output. I suspect, however, that the problem isn't actually with riakpbc, but rather the process running out of memory and being unable to buffer any more data.

I modified your script to keep count in an integer rather than storing all of the actual keys in an array and checking length later, as in:

``` javascript
var getCount = function (next) {

    var count = 0;

    client.getKeys({
        bucket: 'limit-test',
        type: 'custombucket'
    }).on('data', function (reply) {

        count += reply.keys.length;
    }).on('end', function () {

        console.log('There are %d keys', count);
        client.end();
    }).on('error', function (err) {

        console.error(err);
    });
};
```

And now I'm over a million keys and it hasn't failed once.

**Comment by nlf** [comment] 2014-10-22 18:03
Yeah, I can no longer reproduce this issue when storing the count in an integer instead of the keys in an array. Looks like you were just running out of memory. Closing as a non-issue.

**Closed as completed by nlf** 2014-10-22 18:03 UTC
Labels: invalid

**Comment by kylegetson** [comment] 2014-10-22 18:45
Thanks for looking into this. The randomness of this happening seems odd to me, but I agree, I think its unrelated to riakpbc. As long as I don't try to cram that many items into an array like that I seem to be fine, and its not really something I need to do, I just happened to come across this when testing out riakpbc. Thanks!
