### ISSUE TITLE
Trouble keeping connection with riak

### ISSUE THREAD

**Issue by larseen** [nlf/riakpbc#72] opened 2014-08-28 21:29 UTC
This is a bit hard to explain, however it is a real problem that i can not seem to figure out.
I have a Ubuntu machine with a node.js server, getting its data from riak and sending it back. It worked fine for about a week, but now it seems that i can connect with riak but only make one request before i loose the connection. 
I have tried running the server on several other computers which worked fine, I also tried the auto_connect option, which however does not seem to fix the problem.
Any ideas?

**Comment by nlf** [comment] 2014-08-28 21:31
That's a tough one.. Unless you can figure out a way to reproduce it, I'm not sure what I can do. It's possible that some error is causing the connection to get caught in a bad state, but I can't say for sure.

**Comment by larseen** [comment] 2014-08-28 23:02
There is no problem running single get value for key in bucket command, like the example below:

```
    db.get({ bucket: 'product', key: req.params.productID }, function (err, reply) {
                if(err) return res.send(500, { error: {code: 99, message: err.message}});
                if (!reply.hasOwnProperty("content")) {
                    return res.send(200, { error: {code: 1, message: "No product found with this id"}});
                }
                return res.send(reply.content[0].value);
            });
```

I loose my connection when doing nested queries, like below i get a list of keys from the riak. But when i am making a connection for getting each of the values for the respective keys, both my reply and err is undefined, most likely because i have no connection with riak.

```
            db.get({ bucket: 'active_product', key: appId},function (err, reply) {
                if(err) {
                    return res.send(500, {error: {code: 99, message: err.message}});
                }
                if(!reply.hasOwnProperty("content")){
                    return res.send(200, {error: {code: 98, message: "No active products collection found on appId:" + appId}})
                }
                var active_products = reply.content[0].value;
                //Then get the keys for all products.
                db.getKeys({ bucket: 'product'},function (err, reply) {
                    if(err) {
                        return res.send(500, {error: {code: 99, message: err.message}});
                    }
                    var keys = reply.keys;
                    var products = [];
```

**Comment by nlf** [comment] 2014-08-28 23:28
`err` is undefined too? If the connection fails, it should be at least giving you an error.. Doing some testing on my end too.

What version of riakpbc are you using?

**Comment by larseen** [comment] 2014-08-28 23:37
Im using 1.4.2, I dont think its possible to recreate, i can run this same server on several other machines, they work, however the server that worked before is now acting like this.
I even tried reformatting the whole computer and installing riak+node, etc. agian.

**Comment by nlf** [comment] 2014-08-28 23:45
Can you check your logs for riak to see if there any errors there?

**Comment by larseen** [comment] 2014-08-28 23:54
Oh yeah, there is some errors, here is the crashLog http://pastebin.com/FAT3HLK9

**Comment by nlf** [comment] 2014-08-28 23:59
What version of riak are you using?

**Comment by larseen** [comment] 2014-08-29 00:00
Version 1.4.10

**Comment by nlf** [comment] 2014-08-29 00:02
From your crash log, it looks like you may have some data corruption in your riak database. I asked in #riak on freenode and it sounds like the invalid hint errors typically come from corrupt data on disk.

Do other clients still work? For example, can you use the http interface and list keys?

**Comment by larseen** [comment] 2014-08-29 00:27
Ok, thanks!

I have to check it tomorrow, however it does sound likely, and i should have checked it before.
Moments before all this problems occurred we had a power failure while using the system, and the identical node for this server was not up an running since the system was so new. So it had no chance to fix the corrupted data.
I will give you an update, and apologize for bothering you.

**Comment by nlf** [comment] 2014-08-29 00:38
No need to apologize at all, I believe there actually is a bug in riakpbc anyway as it should've returned an error in the reply instead of `undefined`. I'll see what I can do.

**Comment by larseen** [comment] 2014-08-29 00:42
If i remembered correctly so did it return an object, however this was undefined, so when I tried to respond reply.content[0].value, the whole program crashed.

**Comment by larseen** [comment] 2014-08-31 21:47
So riak did have some corrupted data that we fixed, however I am experiencing some rather troubling problem, something vi did not have before.
When we now get the list of all the keys in the bucket and are running a nested query for getting the objects corresponding to those keys sometimes riakpbc return empty replies.
It works if i check for empty replies with an if statement but it means that I loose data sometimes a lot other times Ill get everything. 
Very troublesome bug.

**Comment by nlf** [comment] 2014-09-08 18:24
Are these keys that have just been written? Or are they keys that have existed consistently? I'm unable to reproduce this one, so my hunch is you may need to tune your `w` and `r` values to get a better consensus on writes and reads.

**Comment by nlf** [comment] 2014-09-17 17:28
Closing this, I'm completely unable to reproduce it. @larseen if you manage to reproduce this in a test case, feel free to reopen the issue.

**Closed as completed by nlf** 2014-09-17 17:28 UTC
Labels: bug, invalid
